### ISSUE TITLE
Topic modeling

### ISSUE THREAD

**Issue by justram** [justram/news_retrieval#1]
Provide simple LDA topic model demo with wikipedia, which includes:
1. Basic LDA model introduction
2. LDA tuning methods
3. Visualization of LDA analysis

**Comment by alicianingchen** [comment]
1. Basic LDA model introduction
LDA：隱含狄利克雷分佈（Latent Dirichlet Allocation，簡稱LDA） 
定義: 
-它是一種主題模型，它可以將文件集中每篇文件的主題以概率分佈的形式給出，從而通過分析一些文件抽取出它們的主題（分佈）出來後，便可以根據主題（分佈）進行主題聚類或文字分類。同時，它是一種典型的詞袋模型，即一篇文件是由一組詞構成，詞與詞之間沒有先後順序的關係。
更詳細介紹：
https://taweihuang.hpd.io/2019/01/10/topic-modeling-lda/
https://www.itread01.com/content/1547908949.html
預估research 時間：3~4小時

**Comment by alicianingchen** [comment]
2. LDA tuning methods
找到一些資料還在研究當中先丟上來大家看看
詳細講解：
1: https://zhuanlan.zhihu.com/p/31470216
2: https://www.itread01.com/content/1545463658.html
預估時間：很久？

**Comment by hyusterr** [comment]
LDA 模型
搞懂模型 ( 原理 )   >>> 5-6小時 
實作在維基百科上 
    爬維基百科文本 >>> 5-6 小時寫程式碼 + 等資料跑完 (難估計時間)
    前處理               >>> 6+小時寫程式碼 還不算跑程式的時間 這要看文本的長相
    刻模型               >>> 這部分我比較沒經驗，應該耗時較久，10 - 15 小時左右，可能更多
    調參數               >>> 看效果如何，感覺不能完全跟刻模型分開，應該也是 10 - 15 小時左右 ?
視覺化結果            >>> 如果前面的工作都順利，應該 6 小時左右可以完成

**Comment by dibery** [comment]
要實作 LDA 的話，python 有[套件](https://pypi.org/project/lda/)可用，應該可以省下很多工夫，說明文件[在此](https://lda.readthedocs.io/en/latest/)，如果有需要，我請系統管理員裝一下應該不會太費事。

**Comment by justram** [comment]
1st sprint over. Plz commit current script or docs(if necessary). @hyusterr  @elaine76
