### ISSUE TITLE
News/exchange rate collect

### ISSUE THREAD

**Issue by justram** [justram/news_retrieval#2]
Collect news/exchange rate from EU/US, period: 2018-2019
1. Find top subscribed news in EU/US
2. Parse news as XML/JSON/CBOR format
3. Parse exchange rate as simple log with timestamp

**Comment by dibery** [comment]
### 第三項細部說明

1. 歷史匯率查詢，可自[臺灣期貨交易所](https://www.taifex.com.tw/cht/3/dailyFXRate)下載
2. 缺點為一次只能載一年、大五編碼
3. 好處是涵蓋自 2008/8/1 起每日 EUR 對 USD 的匯率（完全就是我們要的，而且有 CSV 可以下載）
4. 預估時程：2~3H

註：時間的細度只到一天，沒有人會把每分鐘的匯率都存在歷史紀錄檔裡，這必須妥協

**Comment by dibery** [comment]
### 第一項細部說明（草稿）

- [New York Times](https://www.nytimes.com/)
有名的美國報紙，可爬歷史新聞，但範圍僅限報紙上的，一般導向的新聞，下載難易度大約 C 級 (SS~H)
[2017/12/19前連結範例](https://archive.nytimes.com/www.nytimes.com/indexes/2017/12/19/todayspaper/index.html)
[2017/12/20後連結範例](https://www.nytimes.com/issue/todayspaper/2017/12/20/todays-new-york-times)
- [Wall Streets Journal](https://www.wsj.com/)
有名的美國財經報紙，可爬歷史新聞，但僅限一年內（敗筆）

**Comment by hyusterr** [comment]
[歐洲央行的美元兌歐元歷史資料](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/eurofxref-graph-usd.en.html)
可以看到1999年以來歐元兌美元匯率的歷史資料
看了網站原始碼，感覺不是太難爬下資料

[ECB首頁](https://www.ecb.europa.eu/home/html/index.en.html)
有不少歐洲央行官方的新聞

[FED首頁](https://www.federalreserve.gov/newsevents/pressreleases.htm)
美國聯準會，專門管美元的，官方新聞是美元重要指標。

[Bloomberg](https://www.bloomberg.com/)
財經界重要新聞，有按地區分類，算是比較權威的消息來源。

**Comment by hyusterr** [comment]
找可靠的新聞來源      >>> 大概 3-4 小時，我會去問在財金領域實習的朋友
爬取新聞資料並整理   >>> 這因網站的長相不同而異，如果每個不同的網站都爬下來的話大概，20多小時？
爬取歐元美元匯率       >>> 從ECB的網站抓應該 3 小時以內

**Comment by elaine76** [comment]
第一項細部說明：
1.找美國/歐洲市場相關新聞，根據銀行圈內trader的調查，多數相關觀看新聞以
Bloomberg彭博 和Reuter 路透社為主。
目前查詢有相關財金/經濟市場相關媒體網站：Time/Newsweek/The New York Times/DW/BBC News
Voanews/Financial Times/Euronews
建議除了主要兩個之外，是否需要再多其他的媒體網站可以討論。
注意：Trader以每日發生的事件來做評斷與辨別依據。所以新聞必須涵蓋所有歐美每日的事件發生。

3. 外匯匯率網站一般來說，台灣各大銀行都有相關歷史匯率，以天為主。如果以台灣期貨交易所我個人認為不客觀。因為銀行內部的換匯不會只看期貨交易所的所有匯率。端看是否要看大一點。建議找歐洲央行或美國的來爬相關的所有匯率。

不過時間點：我想了解的是玉山是否有想要做到每分鐘爬取匯率資訊？還是以天為主？因為正常來說
匯率是每分鐘都會波動的。根據他們想要以新聞重要性，提供更準確的新聞給trader的話，基本上應該是會非常在意每一分鐘的匯率變化，來決定是否做交易。

上述抓取時間，要端看每個網站的架構不同，還有要抓取的時間長短不同而異。大致上1小時抓一個月？？不很確定。。。。。
以上。簡略說明請參酌。謝謝

**Comment by dibery** [comment]
路透的新聞我有看過，雖然有名，但是我找不到地方可以看到歷史新聞，以目前要訓練資料的話會比較麻煩，至於彭博我倒是還沒看過網頁格式，不確定歷史新聞是否好找。除了新聞的使用狀況，我覺得資料取得的難易度也得考慮進來。

匯率每分都會波動是可預期，找央行倒是沒什麼問題，只是歷史資訊也是只有日等級的？

**Comment by justram** [comment]
1st sprint over. Plz commit current script or docs(if necessary). @dibery @alicianingchen
